# coding: utf-8

"""
    Aeternity Epoch

    This is the [Aeternity](https://www.aeternity.com/) Epoch API.

    OpenAPI spec version: 1.0.0
    Contact: apiteam@aeternity.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NamePreclaimTx(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'commitment': 'str',
        'fee': 'int'
    }

    attribute_map = {
        'commitment': 'commitment',
        'fee': 'fee'
    }

    def __init__(self, commitment=None, fee=None):
        """
        NamePreclaimTx - a model defined in Swagger
        """

        self._commitment = None
        self._fee = None

        self.commitment = commitment
        self.fee = fee

    @property
    def commitment(self):
        """
        Gets the commitment of this NamePreclaimTx.

        :return: The commitment of this NamePreclaimTx.
        :rtype: str
        """
        return self._commitment

    @commitment.setter
    def commitment(self, commitment):
        """
        Sets the commitment of this NamePreclaimTx.

        :param commitment: The commitment of this NamePreclaimTx.
        :type: str
        """
        if commitment is None:
            raise ValueError("Invalid value for `commitment`, must not be `None`")

        self._commitment = commitment

    @property
    def fee(self):
        """
        Gets the fee of this NamePreclaimTx.

        :return: The fee of this NamePreclaimTx.
        :rtype: int
        """
        return self._fee

    @fee.setter
    def fee(self, fee):
        """
        Sets the fee of this NamePreclaimTx.

        :param fee: The fee of this NamePreclaimTx.
        :type: int
        """
        if fee is None:
            raise ValueError("Invalid value for `fee`, must not be `None`")

        self._fee = fee

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NamePreclaimTx):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
