# coding: utf-8

"""
    Aeternity Epoch

    This is the [Aeternity](https://www.aeternity.com/) Epoch API.

    OpenAPI spec version: 1.0.0
    Contact: apiteam@aeternity.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NameClaimTx(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'name_salt': 'int',
        'fee': 'int'
    }

    attribute_map = {
        'name': 'name',
        'name_salt': 'name_salt',
        'fee': 'fee'
    }

    def __init__(self, name=None, name_salt=None, fee=None):
        """
        NameClaimTx - a model defined in Swagger
        """

        self._name = None
        self._name_salt = None
        self._fee = None

        self.name = name
        self.name_salt = name_salt
        self.fee = fee

    @property
    def name(self):
        """
        Gets the name of this NameClaimTx.

        :return: The name of this NameClaimTx.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this NameClaimTx.

        :param name: The name of this NameClaimTx.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def name_salt(self):
        """
        Gets the name_salt of this NameClaimTx.

        :return: The name_salt of this NameClaimTx.
        :rtype: int
        """
        return self._name_salt

    @name_salt.setter
    def name_salt(self, name_salt):
        """
        Sets the name_salt of this NameClaimTx.

        :param name_salt: The name_salt of this NameClaimTx.
        :type: int
        """
        if name_salt is None:
            raise ValueError("Invalid value for `name_salt`, must not be `None`")

        self._name_salt = name_salt

    @property
    def fee(self):
        """
        Gets the fee of this NameClaimTx.

        :return: The fee of this NameClaimTx.
        :rtype: int
        """
        return self._fee

    @fee.setter
    def fee(self, fee):
        """
        Sets the fee of this NameClaimTx.

        :param fee: The fee of this NameClaimTx.
        :type: int
        """
        if fee is None:
            raise ValueError("Invalid value for `fee`, must not be `None`")

        self._fee = fee

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NameClaimTx):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
