# coding: utf-8

"""
    Aeternity Epoch

    This is the [Aeternity](https://www.aeternity.com/) Epoch API.

    OpenAPI spec version: 1.0.0
    Contact: apiteam@aeternity.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NameTransferTx(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name_hash': 'str',
        'recipient_pubkey': 'str',
        'fee': 'int'
    }

    attribute_map = {
        'name_hash': 'name_hash',
        'recipient_pubkey': 'recipient_pubkey',
        'fee': 'fee'
    }

    def __init__(self, name_hash=None, recipient_pubkey=None, fee=None):
        """
        NameTransferTx - a model defined in Swagger
        """

        self._name_hash = None
        self._recipient_pubkey = None
        self._fee = None

        self.name_hash = name_hash
        self.recipient_pubkey = recipient_pubkey
        self.fee = fee

    @property
    def name_hash(self):
        """
        Gets the name_hash of this NameTransferTx.

        :return: The name_hash of this NameTransferTx.
        :rtype: str
        """
        return self._name_hash

    @name_hash.setter
    def name_hash(self, name_hash):
        """
        Sets the name_hash of this NameTransferTx.

        :param name_hash: The name_hash of this NameTransferTx.
        :type: str
        """
        if name_hash is None:
            raise ValueError("Invalid value for `name_hash`, must not be `None`")

        self._name_hash = name_hash

    @property
    def recipient_pubkey(self):
        """
        Gets the recipient_pubkey of this NameTransferTx.

        :return: The recipient_pubkey of this NameTransferTx.
        :rtype: str
        """
        return self._recipient_pubkey

    @recipient_pubkey.setter
    def recipient_pubkey(self, recipient_pubkey):
        """
        Sets the recipient_pubkey of this NameTransferTx.

        :param recipient_pubkey: The recipient_pubkey of this NameTransferTx.
        :type: str
        """
        if recipient_pubkey is None:
            raise ValueError("Invalid value for `recipient_pubkey`, must not be `None`")

        self._recipient_pubkey = recipient_pubkey

    @property
    def fee(self):
        """
        Gets the fee of this NameTransferTx.

        :return: The fee of this NameTransferTx.
        :rtype: int
        """
        return self._fee

    @fee.setter
    def fee(self, fee):
        """
        Sets the fee of this NameTransferTx.

        :param fee: The fee of this NameTransferTx.
        :type: int
        """
        if fee is None:
            raise ValueError("Invalid value for `fee`, must not be `None`")

        self._fee = fee

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NameTransferTx):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
