# coding: utf-8

"""
    Aeternity Epoch

    This is the [Aeternity](https://www.aeternity.com/) Epoch API.

    OpenAPI spec version: 1.0.0
    Contact: apiteam@aeternity.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NameEntry(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'name_ttl': 'int',
        'pointers': 'str'
    }

    attribute_map = {
        'name': 'name',
        'name_ttl': 'name_ttl',
        'pointers': 'pointers'
    }

    def __init__(self, name=None, name_ttl=None, pointers=None):
        """
        NameEntry - a model defined in Swagger
        """

        self._name = None
        self._name_ttl = None
        self._pointers = None

        if name is not None:
          self.name = name
        if name_ttl is not None:
          self.name_ttl = name_ttl
        if pointers is not None:
          self.pointers = pointers

    @property
    def name(self):
        """
        Gets the name of this NameEntry.

        :return: The name of this NameEntry.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this NameEntry.

        :param name: The name of this NameEntry.
        :type: str
        """

        self._name = name

    @property
    def name_ttl(self):
        """
        Gets the name_ttl of this NameEntry.

        :return: The name_ttl of this NameEntry.
        :rtype: int
        """
        return self._name_ttl

    @name_ttl.setter
    def name_ttl(self, name_ttl):
        """
        Sets the name_ttl of this NameEntry.

        :param name_ttl: The name_ttl of this NameEntry.
        :type: int
        """

        self._name_ttl = name_ttl

    @property
    def pointers(self):
        """
        Gets the pointers of this NameEntry.

        :return: The pointers of this NameEntry.
        :rtype: str
        """
        return self._pointers

    @pointers.setter
    def pointers(self, pointers):
        """
        Sets the pointers of this NameEntry.

        :param pointers: The pointers of this NameEntry.
        :type: str
        """

        self._pointers = pointers

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NameEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
